services:
  postgres:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  minio:
    env_file: 
      - .env.test.local
    image: minio/minio
    container_name: "people-minio"
    command: server --console-address ":9001" /data
    ports:
      - "${MINIO_PORT_1}:9000"
      - "${MINIO_PORT_2}:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    
  redis:
    image: redis:alpine3.16
    container_name: redis-wsbe
    env_file: .env.test.local
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "6379:6379"
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    hostname: kafka
    networks: [ app_network ]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # кворум контроллеров. Один узел — один голос
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # обычные параметры
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      CLUSTER_ID: 'q1Sh-9_ISia_zwGINzRvyQ'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on: [ kafka ]
    networks: [ app_network ]
    ports: [ "8080:8080" ]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
  
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    networks: [app_network]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongo_data:/data/db
  
  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    restart: unless-stopped
    depends_on: [mongo]
    networks: [app_network]
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  minio_data:
  pgadmin-data:
  mongo_data:


networks:
  app_network:
    driver: bridge